# Generated by Django 6.0.6 on 2026-08-12 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(help_text='Contoh: PT Retail Nusantara Sejahtera', max_length=150)),
                ('kode_perusahaan', models.CharField(help_text='Contoh: RNS', max_length=20, unique=True)),
                ('nib', models.CharField(blank=True, help_text='Nomor Induk Berusaha (NIB)', max_length=50, null=True, unique=True)),
                ('npwp', models.CharField(blank=True, help_text='NPWP Badan Usaha / Perusahaan', max_length=50, null=True, unique=True)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
            ],
            options={
                'verbose_name': 'Profil Perusahaan',
                'verbose_name_plural': 'Profil Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_site', models.CharField(help_text='Contoh: HO-01, DC-01, TKO-01', max_length=20, unique=True)),
                ('nama_site', models.CharField(max_length=100)),
                ('tipe_site', models.CharField(choices=[('DC', 'Distribution Center / Gudang Utama'), ('STORE', 'Toko Cabang / Store'), ('HO', 'Head Office / Kantor Pusat')], default='STORE', max_length=10)),
                ('npwp_cabang', models.CharField(blank=True, help_text='NPWP Cabang (jika ada pendaftaran khusus lokasi)', max_length=50, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('replenishment_schedule_days', models.CharField(blank=True, default='MON,THU', help_text='Hari jadwal replenishment (khusus Store), contoh: MON,THU', max_length=50, null=True)),
                ('company', models.ForeignKey(help_text='Perusahaan induk site ini', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.companyprofile')),
            ],
            options={
                'verbose_name': 'Master Site (DC & Toko)',
                'verbose_name_plural': 'Master Site (DC & Toko)',
            },
        ),
        migrations.CreateModel(
            name='UserSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, help_text='Contoh: Store Manager, Kasir, Inventory Control', max_length=100, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_site', models.ForeignKey(help_text='Site/Cabang tempat user ini bertugas', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_users', to='core.sitelocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Akses Site User',
                'verbose_name_plural': 'Akses Site User',
            },
        ),
    ]
