# Generated by Django 6.0.6 on 2026-08-10 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Divisi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Divisi',
                'verbose_name_plural': 'Divisi',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name': 'Distributor', 'verbose_name_plural': 'Distributor'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Master Item', 'verbose_name_plural': 'Master Item'},
        ),
        migrations.AlterModelOptions(
            name='pricerule',
            options={'verbose_name': 'Aturan Harga', 'verbose_name_plural': 'Aturan Harga'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Prinsipal', 'verbose_name_plural': 'Prinsipal'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Supplier'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak Person'),
        ),
        migrations.AddField(
            model_name='item',
            name='active_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='merchandise.supplier', verbose_name='Pemasok Aktif'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_carton',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barcode Carton (CTN)'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_pack',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barcode Pack'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barcode Satuan'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Jual (Retail Price)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='returnable',
            field=models.BooleanField(default=True, verbose_name='Dapat Diretur (Returnable)'),
        ),
        migrations.AddField(
            model_name='item',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Singkat (Struk/Label)'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20, verbose_name='Status Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(default='Pcs', max_length=20, verbose_name='Satuan (UOM)'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Terakhir Diubah'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='pricerule',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Aturan Harga'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchandise.principal', verbose_name='Prinsipal'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('principal', 'Prinsipal Langsung'), ('distributor', 'Distributor Resmi')], default='distributor', max_length=20, verbose_name='Tipe Pemasok'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nama Distributor'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telepon'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='merchandise.principal', verbose_name='Prinsipal Terkait'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='merchandise.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Beli (Cost Price)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif (Legacy)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nama Lengkap Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kode SKU / Item Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stok Minimum'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Berakhir'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='merchandise.item', verbose_name='Item Produk'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='min_qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12, verbose_name='Min. Kuantitas'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='special_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Khusus'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mulai Berlaku'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak Person'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nama Prinsipal'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telepon'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='merchandise.distributor', verbose_name='Distributor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nama Pemasok'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telepon'),
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='merchandise.department', verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='merchandise.division', verbose_name='Divisi'),
        ),
        migrations.CreateModel(
            name='PromoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Judul Program Promo')),
                ('promo_type', models.CharField(choices=[('nominal_discount', 'Potongan Harga Nominal'), ('percentage_discount', 'Diskon Persentase'), ('bogo', 'Buy 1 Get 1 Free'), ('bundle', 'Bundle Package'), ('gwp', 'Gift with Purchase')], max_length=30, verbose_name='Mekanisme Promo')),
                ('start_date', models.DateTimeField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateTimeField(verbose_name='Tanggal Selesai')),
                ('min_purchase_qty', models.PositiveIntegerField(default=1, verbose_name='Min. Kuantitas Pembelian')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Min. Belanja (Rp)')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Syarat & Ketentuan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('items', models.ManyToManyField(blank=True, related_name='promos', to='merchandise.item', verbose_name='Target Item Spesifik')),
            ],
            options={
                'verbose_name': 'Pengaturan Promo',
                'verbose_name_plural': 'Pengaturan Promo',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Subkategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='merchandise.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Subkategori',
                'verbose_name_plural': 'Subkategori',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='merchandise.subcategory', verbose_name='Subkategori'),
        ),
    ]
