# Generated by Django 6.0.6 on 2026-08-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_department_division_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dept', models.CharField(help_text='Contoh: 0101 (Beverages)', max_length=10, unique=True)),
                ('nama_dept', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_divisi', models.CharField(help_text='Contoh: 01 (Food)', max_length=10, unique=True)),
                ('nama_divisi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Divisi',
                'verbose_name_plural': 'Divisi',
            },
        ),
        migrations.RemoveField(
            model_name='department',
            name='division',
        ),
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='promosetting',
            name='items',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Category', 'verbose_name_plural': 'Sub-Category'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Master Supplier', 'verbose_name_plural': 'Master Supplier'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='active_supplier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode_carton',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode_pack',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='returnable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_minimum',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_type',
        ),
        migrations.AddField(
            model_name='category',
            name='kode_category',
            field=models.CharField(blank=True, help_text='Contoh: 010101 (Soft Drinks)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nama_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN / UPC Barcode', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_beli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Jual / HET'),
        ),
        migrations.AddField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='satuan',
            field=models.CharField(default='PCS', help_text='PCS, CTN, BOX', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='sku_internal',
            field=models.CharField(blank=True, help_text='Contoh: ITM-88902', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_barang',
            field=models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued'), ('Temporary', 'Temporary')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandise.subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandise.supplier'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='kode_sub',
            field=models.CharField(blank=True, help_text='Contoh: 010101001 (Cola 330ml)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='nama_sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kode_supplier',
            field=models.CharField(blank=True, help_text='Contoh: SUP-00123', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kontak_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nama_perusahaan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='npwp_pkp_nib',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Legalitas (NPWP/NIB)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sistem_pesanan',
            field=models.CharField(blank=True, choices=[('Direct Delivery', 'Direct Delivery'), ('Warehouse Supply', 'Warehouse Supply')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telepon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='top_days',
            field=models.IntegerField(default=30, verbose_name='Term of Payment (TOP Hari)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='merchandise.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='merchandise.dept'),
        ),
        migrations.AddField(
            model_name='dept',
            name='divisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='merchandise.divisi'),
        ),
        migrations.CreateModel(
            name='Promosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_promosi', models.CharField(max_length=150)),
                ('jenis_promosi', models.CharField(choices=[('Diskon Harga', 'Diskon Harga Langsung'), ('Bundling', 'Bundling / Multipack'), ('GWP', 'Gift with Purchase (GWP)')], max_length=50)),
                ('nilai_diskon', models.DecimalField(decimal_places=2, help_text='Dalam % atau nominal', max_digits=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_berakhir', models.DateField()),
                ('pendanaan', models.CharField(choices=[('Joint Promo (Supplier)', 'Joint Promo (Supplier)'), ('Retailer Margin', 'Retailer Margin')], max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='merchandise.item')),
            ],
            options={
                'verbose_name': 'Promosi',
                'verbose_name_plural': 'Promosi',
            },
        ),
        migrations.CreateModel(
            name='PushOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_alokasi', models.CharField(help_text='Allocation Order Number', max_length=30, unique=True)),
                ('tanggal_distribusi', models.DateField()),
                ('toko_tujuan', models.CharField(help_text='Nama Cabang Toko', max_length=100)),
                ('qty_alokasi', models.PositiveIntegerField(help_text='Jumlah alokasi dari pusat')),
                ('keterangan', models.TextField(blank=True, help_text='Berdasarkan analisis kapasitas rak & sales history', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.item')),
            ],
            options={
                'verbose_name': 'Push Order (Alokasi)',
                'verbose_name_plural': 'Push Order (Alokasi)',
            },
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='PriceRule',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.DeleteModel(
            name='PromoSetting',
        ),
    ]
