# Generated by Django 6.0.6 on 2026-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_dept_divisi_remove_department_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku_internal',
            field=models.CharField(blank=True, help_text='Generate otomatis dari kode sub-kategori + running number', max_length=20, null=True, unique=True),
        ),
    ]
