# Generated by Django 6.0.6 on 2026-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_alter_item_sku_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='harga_beli',
        ),
        migrations.RemoveField(
            model_name='promosi',
            name='pendanaan',
        ),
        migrations.AddField(
            model_name='item',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Katalog (List Price)'),
        ),
        migrations.AddField(
            model_name='item',
            name='diskon_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Persen Diskon 1', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='diskon_2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Persen Diskon 2', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='diskon_3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Persen Diskon 3', max_digits=5),
        ),
        migrations.AddField(
            model_name='promosi',
            name='harga_promo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Khusus Promo'),
        ),
        migrations.AddField(
            model_name='promosi',
            name='sumber_pendanaan',
            field=models.CharField(choices=[('Supplier', 'Supplier Funded'), ('Retailer', 'Retailer Margin'), ('Sharing', 'Joint Sharing')], default='Supplier', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='kode_category',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='kode_dept',
            field=models.CharField(blank=True, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='divisi',
            name='kode_divisi',
            field=models.CharField(blank=True, max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Jual Reguler (HET)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku_internal',
            field=models.CharField(blank=True, help_text='Generate otomatis dari sub-kategori', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promosi',
            name='jenis_promosi',
            field=models.CharField(choices=[('Diskon Harga', 'Diskon Harga Langsung'), ('Bundling', 'Bundling / Multipack'), ('GWP', 'Gift with Purchase (GWP)')], default='Diskon Harga', max_length=50),
        ),
        migrations.AlterField(
            model_name='promosi',
            name='nilai_diskon',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dalam % atau nominal', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='kode_sub',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
