# Generated by Django 6.0.6 on 2026-08-11 14:18

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_remove_item_harga_beli_remove_promosi_pendanaan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku_internal',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status_barang',
        ),
        migrations.AddField(
            model_name='item',
            name='article_supplier_code',
            field=models.CharField(blank=True, help_text='Kode barang dari faktur supplier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='article_supplier_name',
            field=models.CharField(blank=True, help_text='Nama produk persis sesuai faktur supplier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_ctn',
            field=models.CharField(blank=True, help_text='Barcode carton/kardus', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_inner',
            field=models.CharField(blank=True, help_text='Barcode inner pack', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_internal',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='gross_margin_persen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Margin kotor dihitung dari Harga Jual Non-PPN vs Harga Beli Non-PPN', max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_beli_non_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_beli_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_jual_non_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_jual_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Terupdate otomatis jika ada promo aktif', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isi_carton',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah satuan terkecil di dalam 1 Carton'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='plu_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ppn_beli_persen',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Persentase PPN Beli (misal: 11%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='ppn_jual_persen',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Persentase PPN Jual (misal: 11%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='promo_berakhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='promo_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='short_nama',
            field=models.CharField(blank=True, help_text='Nama ringkas untuk cetak struk kasir (POS)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status_store',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('TEMPORARY', 'Temporary / Seasonal'), ('BLOCKED', 'Blocked for Ordering')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode pabrik / EAN / UPC satuan terkecil', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(blank=True, help_text='Nama lengkap (Long Name)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan',
            field=models.CharField(choices=[('PCS', 'Pcs'), ('KG', 'Kilogram (Kg)'), ('GRAM', 'Gram'), ('PACK', 'Pack'), ('BOX', 'Box'), ('CTN', 'Carton'), ('BOTOL', 'Botol'), ('LITER', 'Liter'), ('SET', 'Set')], default='PCS', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='kode_sub',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
