# Generated by Django 6.0.6 on 2026-08-11 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_alter_category_options_remove_item_sku_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='harga_beli_non_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_jual_non_ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_store',
            field=models.CharField(choices=[('ACTIVE', 'Active: Normal (Bisa Pesan & Jual)'), ('TEMPORARY', 'Temporary: Kosong Sementara (No Request, Masih Jual)'), ('DISCONTINUED', 'Discontinued: Tutup Produksi (No Request, Clearance Sale)'), ('BLOCKED', 'Blocked: Dilarang (No Request, No Jual)')], default='ACTIVE', max_length=20),
        ),
    ]
