# Generated by Django 6.0.6 on 2026-08-11 17:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_alter_item_harga_beli_non_ppn_and_more'),
        ('operations', '0003_location_replenishment_schedule_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushorder',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='article_supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='article_supplier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_ctn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_inner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_internal',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='gross_margin_persen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='isi_carton',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='plu_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppn_beli_persen',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppn_jual_persen',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan',
            field=models.CharField(default='PCS', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_store',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kode_supplier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='npwp_pkp_nib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='top_days',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_po', models.CharField(max_length=50, unique=True)),
                ('tipe_po', models.CharField(choices=[('MANUAL', 'PO Manual'), ('REPLENISHMENT', 'PO Replenishment (21 Hari)')], default='MANUAL', max_length=20)),
                ('tanggal_po', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('lokasi_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchandise_purchase_orders', to='operations.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchandise_purchase_orders', to='merchandise.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order (Eksternal)',
                'verbose_name_plural': 'Purchase Order (Eksternal)',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_order', models.PositiveIntegerField(default=1)),
                ('harga_beli_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchandise_po_items', to='merchandise.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandise.purchaseorder')),
            ],
        ),
        migrations.DeleteModel(
            name='Promosi',
        ),
        migrations.DeleteModel(
            name='PushOrder',
        ),
    ]
