# Generated by Django 6.0.6 on 2026-08-11 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_remove_pushorder_item_item_net_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal_po',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tipe_po',
            field=models.CharField(choices=[('MANUAL', 'PO Manual'), ('REPLENISHMENT', 'PO Replenishment (14 Hari Otomatis)')], default='MANUAL', max_length=20),
        ),
    ]
