# Generated by Django 6.0.6 on 2026-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_alter_purchaseorder_tanggal_po_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Order'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tipe_po',
            field=models.CharField(choices=[('DIRECT', 'Direct Order'), ('REPLENISHMENT', 'Replenishment Order')], default='DIRECT', max_length=20),
        ),
    ]
