# Generated by Django 6.0.6 on 2026-08-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('merchandise', '0010_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='lokasi_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchandise_purchase_orders', to='core.sitelocation'),
        ),
    ]
