# Generated by Django 6.0.6 on 2026-08-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0011_alter_purchaseorder_lokasi_tujuan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode_internal',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_pcs_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode PCS (Utama)'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode_pcs_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode PCS (Alternatif/Promo)'),
        ),
        migrations.AddField(
            model_name='item',
            name='isi_inner',
            field=models.IntegerField(default=1, verbose_name='Isi per Innerpack'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article_supplier_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kode Artikel Supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article_supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Artikel Supplier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_ctn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Carton (CTN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode_inner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode Innerpack'),
        ),
        migrations.AlterField(
            model_name='item',
            name='isi_carton',
            field=models.IntegerField(default=1, verbose_name='Isi per Carton'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Kode Internal'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nama_produk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Produk Internal'),
        ),
        migrations.AlterField(
            model_name='item',
            name='plu_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PLU Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan',
            field=models.CharField(default='PCS', max_length=20, verbose_name='Satuan Dasar'),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_nama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Singkat (Struk)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandise.subcategory', verbose_name='Sub Kategori'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchandise.supplier', verbose_name='Supplier Utama'),
        ),
    ]
