# Generated by Django 6.0.6 on 2026-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('merchandise', '0012_remove_item_barcode_remove_item_barcode_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_item',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUE', 'Discontinue'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30, verbose_name='Status Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='store_aktif_penjualan',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipe_site': 'STORE'}, related_name='allowed_items', to='core.sitelocation', verbose_name='Toko yang Diizinkan Menjual'),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Beli (Base Price)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diskon 1 (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diskon 2 (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='diskon_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diskon 3 (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Jual Normal'),
        ),
        migrations.AlterField(
            model_name='item',
            name='harga_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Promo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Net Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppn_beli_persen',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5, verbose_name='PPN Beli (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ppn_jual_persen',
            field=models.DecimalField(decimal_places=2, default=11.0, max_digits=5, verbose_name='PPN Jual (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='promo_berakhir',
            field=models.DateField(blank=True, null=True, verbose_name='Periode Promo Berakhir'),
        ),
        migrations.AlterField(
            model_name='item',
            name='promo_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Periode Promo Mulai'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_store',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20, verbose_name='Status Store'),
        ),
    ]
