# Generated by Django 6.0.6 on 2026-08-11 15:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0007_alter_item_harga_beli_non_ppn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_lokasi', models.CharField(help_text='Contoh: DC-01, TKO-01', max_length=20, unique=True)),
                ('nama_lokasi', models.CharField(max_length=100)),
                ('tipe_lokasi', models.CharField(choices=[('DC', 'Distribution Center / Gudang Utama'), ('STORE', 'Toko Cabang')], default='STORE', max_length=10)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Master Lokasi',
                'verbose_name_plural': 'Master Lokasi',
            },
        ),
        migrations.CreateModel(
            name='DamageGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_written_off', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.location')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_po', models.CharField(help_text='Nomor PO Pusat', max_length=50, unique=True)),
                ('tanggal_po', models.DateField(auto_now_add=True)),
                ('estimasi_datang', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved / Sent to Supplier'), ('PARTIAL', 'Partial Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lokasi_tujuan', models.ForeignKey(help_text='Tujuan kirim (misal: DC Pusat)', on_delete=django.db.models.deletion.PROTECT, to='operations.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='merchandise.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order (PO)',
                'verbose_name_plural': 'Purchase Order (PO)',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_order', models.PositiveIntegerField(default=1)),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('harga_beli_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi_lokal', models.CharField(help_text='Nomor Struk Kasir Lokal Toko', max_length=50)),
                ('tanggal_transaksi', models.DateTimeField()),
                ('total_belanja', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diskon_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at_backoffice', models.DateTimeField(auto_now_add=True, help_text='Waktu data ditarik/diterima di pusat')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='operations.location')),
            ],
            options={
                'verbose_name': 'Konsolidasi Penjualan (Header)',
                'verbose_name_plural': 'Konsolidasi Penjualan (Header)',
                'unique_together': {('lokasi', 'no_transaksi_lokal')},
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('sales_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.salesheader')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(max_length=100, unique=True)),
                ('transfer_type', models.CharField(choices=[('WH_TO_STORE', 'Gudang ke Toko'), ('STORE_TO_STORE', 'Antar Toko'), ('STORE_TO_WH', 'Toko ke Gudang (Retur)')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='operations.location')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='operations.location')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Disetujui Gudang'), ('REJECTED', 'Ditolak'), ('COMPLETED', 'Selesai Dikirim')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='operations.location')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='operations.storerequisition')),
            ],
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sisa Stok Fisik Aktif', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='merchandise.item')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='operations.location')),
            ],
            options={
                'verbose_name': 'Konsolidasi Stok Lokasi',
                'verbose_name_plural': 'Konsolidasi Stok Lokasi',
                'unique_together': {('lokasi', 'item')},
            },
        ),
    ]
