# Generated by Django 6.0.6 on 2026-08-11 16:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_alter_item_harga_beli_non_ppn_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventorySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shelf_capacity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('target_days_stock', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to='merchandise.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='operations.location')),
            ],
            options={
                'verbose_name': 'Pengaturan Stok Toko',
                'verbose_name_plural': 'Pengaturan Stok Toko',
                'unique_together': {('store', 'item')},
            },
        ),
    ]
