# Generated by Django 6.0.6 on 2026-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_storeinventorysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='replenishment_schedule_days',
            field=models.CharField(default='MON,THU', help_text='Hari jadwal replenishment, contoh: MON,THU (Senin, Kamis)', max_length=50),
        ),
    ]
