# Generated by Django 6.0.6 on 2026-08-12 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_alter_purchaseorder_options_and_more'),
        ('operations', '0003_location_replenishment_schedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='lokasi_tujuan',
            field=models.ForeignKey(help_text='Tujuan kirim (misal: DC Pusat)', limit_choices_to={'tipe_lokasi': 'DC'}, on_delete=django.db.models.deletion.PROTECT, to='operations.location'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='lokasi',
            field=models.ForeignKey(limit_choices_to={'tipe_lokasi': 'STORE'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='operations.location'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('WH_TO_STORE', 'Gudang ke Toko (Replenishment 2 Hari)'), ('STORE_TO_STORE', 'Antar Toko'), ('STORE_TO_WH', 'Toko ke Gudang (Retur)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='storeinventorysetting',
            name='store',
            field=models.ForeignKey(limit_choices_to={'tipe_lokasi': 'STORE'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='operations.location'),
        ),
        migrations.AlterField(
            model_name='storerequisition',
            name='store_location',
            field=models.ForeignKey(limit_choices_to={'tipe_lokasi': 'STORE'}, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='operations.location'),
        ),
        migrations.CreateModel(
            name='GoodsReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_gr', models.CharField(help_text='Nomor Goods Receiving / Surat Jalan Masuk', max_length=50, unique=True)),
                ('tanggal_terima', models.DateTimeField(default=django.utils.timezone.now)),
                ('diterima_oleh', models.CharField(blank=True, max_length=100, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received (Barang Masuk)'), ('PUTAWAY_DONE', 'Putaway Completed (Masuk Rak)')], default='RECEIVED', max_length=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receivings', to='operations.purchaseorder')),
                ('warehouse', models.ForeignKey(help_text='Gudang Penerima', limit_choices_to={'tipe_lokasi': 'DC'}, on_delete=django.db.models.deletion.PROTECT, to='operations.location')),
            ],
            options={
                'verbose_name': 'Goods Receiving (Penerimaan PO)',
                'verbose_name_plural': 'Goods Receiving (Penerimaan PO)',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sent', models.PositiveIntegerField(default=0)),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_rak', models.CharField(help_text='Contoh: RACK-A1-01-03', max_length=50, unique=True)),
                ('zona', models.CharField(blank=True, help_text='Contoh: Zona A (Fast Moving)', max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('warehouse', models.ForeignKey(help_text='Gudang/DC tempat rak ini berada', limit_choices_to={'tipe_lokasi': 'DC'}, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='operations.location')),
            ],
            options={
                'verbose_name': 'Master Rak Gudang',
                'verbose_name_plural': 'Master Rak Gudang',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_po', models.PositiveIntegerField(default=0)),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('goods_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.goodsreceiving')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('rak_tujuan', models.ForeignKey(blank=True, help_text='Alamat rak penyimpanan (Putaway)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_items', to='operations.warehouserack')),
            ],
        ),
    ]
