# Generated by Django 6.0.6 on 2026-08-12 16:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('merchandise', '0011_alter_purchaseorder_lokasi_tujuan'),
        ('operations', '0004_alter_purchaseorder_lokasi_tujuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagegoods',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitelocation'),
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='lokasi_tujuan',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='storeinventorysetting',
            name='store',
            field=models.ForeignKey(limit_choices_to={'tipe_site': 'STORE'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='salesheader',
            name='lokasi',
            field=models.ForeignKey(limit_choices_to={'tipe_site': 'STORE'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='storerequisition',
            name='store_location',
            field=models.ForeignKey(limit_choices_to={'tipe_site': 'STORE'}, on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='stocksnapshot',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='goodsreceiving',
            name='warehouse',
            field=models.ForeignKey(help_text='Gudang Penerima', limit_choices_to={'tipe_site': 'DC'}, on_delete=django.db.models.deletion.PROTECT, to='core.sitelocation'),
        ),
        migrations.AlterField(
            model_name='warehouserack',
            name='warehouse',
            field=models.ForeignKey(help_text='Gudang/DC tempat rak ini berada', limit_choices_to={'tipe_site': 'DC'}, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.sitelocation'),
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='po',
        ),
        migrations.AlterField(
            model_name='goodsreceiving',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receivings', to='merchandise.purchaseorder'),
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('PICKING', 'Picking (Pengambilan di Rak)'), ('TRANSIT', 'In Transit (Dalam Pengiriman)'), ('RECEIVED', 'Received (Diterima)')], default='PICKING', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='rack_source',
            field=models.ForeignKey(blank=True, help_text='Asal rak gudang untuk proses picking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.warehouserack'),
        ),
        migrations.AlterField(
            model_name='goodsreceiving',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Menunggu Diterima)'), ('RECEIVED', 'Received (Barang Masuk)'), ('PUTAWAY_DONE', 'Putaway Completed (Masuk Rak)'), ('RETURNED', 'Returned to Supplier (Retur Keluar)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('WH_TO_STORE', 'Gudang ke Toko (Replenishment)'), ('STORE_TO_STORE', 'Antar Toko'), ('STORE_TO_WH', 'Toko ke Gudang (Retur Toko)')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Jumlah kuantitas stok fisik aktual', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='merchandise.item')),
                ('rack', models.ForeignKey(blank=True, help_text='Rak penyimpanan (Opsional jika di Toko)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stocks', to='operations.warehouserack')),
                ('site', models.ForeignKey(help_text='Lokasi Site (DC atau Toko)', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='core.sitelocation')),
            ],
            options={
                'verbose_name': 'Inventory Stock (Stok Rak/Site)',
                'verbose_name_plural': 'Inventory Stock (Stok Rak/Site)',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
