# Generated by Django 6.0.6 on 2026-08-13 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('merchandise', '0011_alter_purchaseorder_lokasi_tujuan'),
        ('operations', '0005_alter_damagegoods_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGondolaRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_gondola', models.CharField(help_text='Contoh: GONDOLA-A1-03', max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('store', models.ForeignKey(limit_choices_to={'tipe_site': 'STORE'}, on_delete=django.db.models.deletion.CASCADE, related_name='gondola_racks', to='core.sitelocation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_retur', models.CharField(max_length=50, unique=True)),
                ('tanggal_retur', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Disetujui'), ('SHIPPED', 'Dikirim ke Supplier'), ('COMPLETED', 'Selesai / Nota Kredit Diterbitkan')], default='DRAFT', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='merchandise.supplier')),
                ('warehouse', models.ForeignKey(limit_choices_to={'tipe_site': 'DC'}, on_delete=django.db.models.deletion.PROTECT, to='core.sitelocation')),
            ],
            options={
                'verbose_name': 'Retur ke Supplier (Warehouse)',
                'verbose_name_plural': 'Retur ke Supplier (Warehouse)',
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_retur', models.PositiveIntegerField(default=0)),
                ('alasan', models.CharField(help_text='Contoh: Barang Rusak / Expired / Cacat Produksi', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchandise.item')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.supplierreturn')),
            ],
        ),
    ]
